{
  "headers": {
    "client_id": "1",
    "client_secret": "1",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.26.8",
    "accept": "*/*",
    "postman-token": "144b0d38-9686-4ee2-be52-56f6467c8791",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "438"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/v1/createEmployee",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/createEmployee",
  "listenerPath": "/api/v1/*",
  "relativePath": "/api/v1/createEmployee",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/v1/createEmployee",
  "rawRequestPath": "/api/v1/createEmployee",
  "remoteAddress": "/127.0.0.1:51932",
  "requestPath": "/api/v1/createEmployee"
}